name: Run test with cicd

on: [ push ]

jobs:
  build and run test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test with pytest
        env:
          CLIENT_SLACK: ${{ secrets.CLIENT_SLACK }}
          TEST: ${{ github.event.pull_request.title }}
          RUNID: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: pytest

      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: report/

      - name: Download Artifact
        if: always()
        uses: actions/download-artifact@v3
        with:
          name: report